In [1]:
import os,sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

src_dir = os.path.abspath(os.pardir)
sys.path[0] = src_dir

np.set_printoptions(threshold=np.inf)

from analysis.CodingScoring import scoreTIPI, normTIPI, stratTIPI

In [2]:
questions = pd.read_csv('../data/External/dataHeadings.csv')
dataRaw = pd.read_csv('../data/External/dataRaw.csv', names=questions.QuestionCode)
df = dataRaw.join(normTIPI(scoreTIPI(dataRaw)))

In [4]:
std_colors = ['blue','green','black','yellow','purple','red','orange','pink']

In [5]:
df_color_OCEAN = df[['FavColor','O','C','E','A','S']][df['FavColor'].str.lower().str.strip().isin(std_colors)]

In [6]:
df_color_OCEAN['FavColor'] = df_color_OCEAN['FavColor'].str.lower().str.strip()

In [7]:
df_color_OCEAN['N'] = 0-df_color_OCEAN['S']
df_color_OCEAN = df_color_OCEAN.drop(columns='S')
df_color_OCEAN = df_color_OCEAN.dropna()

In [11]:
# df_color_OCEAN

In [8]:
for i,color in enumerate(std_colors):
    df_color_OCEAN = df_color_OCEAN.replace(color,i)

In [9]:
X = df_color_OCEAN[['O','C','E','A','N']].values
y = df_color_OCEAN['FavColor'].values

In [13]:
X

array([[ 0.87111501, -1.16315566,  0.34704062, -0.57899029,  0.24200419],
       [ 0.43213345,  1.6644988 ,  0.66287663, -0.57899029, -0.09608493],
       [-0.44582968,  0.95758518,  0.0312046 , -1.80238153, -1.11035229],
       ...,
       [-0.00684811,  1.6644988 , -1.86381151,  0.64440095, -1.11035229],
       [-0.44582968, -0.45624205, -0.91630346, -0.17119321,  2.27053891],
       [-0.88481124, -0.45624205,  0.0312046 , -2.21017862,  1.25627155]])

In [14]:
y

array([5, 1, 0, ..., 1, 4, 7])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)  

In [11]:
rfc = RandomForestClassifier(n_estimators=20,random_state=0) 
rfc.fit(X_train, y_train)  
y_pred = rfc.predict(X_test)
rfc.score(X_test, y_test)

0.2904019688269073

29% accuracy. 8 color choices - 12.5% would be at chance

In [13]:
rfc.feature_importances_

array([0.17460377, 0.22062098, 0.22646022, 0.19868662, 0.17962841])

In [14]:
df_color_OCEAN = stratTIPI(df_color_OCEAN,3)

/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py:194: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [15]:
X = df_color_OCEAN[['O_strat','C_strat','E_strat','A_strat','N_strat']].values
y = df_color_OCEAN['FavColor'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)  

In [16]:
rfc = RandomForestClassifier(n_estimators=20,random_state=0) 
rfc.fit(X_train, y_train)  
y_pred = rfc.predict(X_test)
rfc.score(X_test, y_test)

0.36587366694011486

36% accuracy - 3x better than chance

In [24]:
X_test

array([[-1,  1, -1,  0, -1],
       [ 1,  0,  1,  0,  0],
       [ 0, -1,  0,  1,  0],
       ...,
       [ 0,  0, -1,  0,  0],
       [-1,  1,  0,  0,  0],
       [-1,  0, -1,  0,  1]])

In [26]:
rfc.predict([[1,0,0,0,0]])

array([0])

In [30]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 5, 0, 0, 0, 0, 4, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 5, 6, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 1, 0, 4, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 4, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 4, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 4, 4, 0, 0, 0, 0, 0, 0, 4, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 4, 0, 0, 1, 0,

In [17]:
rfc.feature_importances_

array([0.23190461, 0.20121586, 0.23274964, 0.16395169, 0.1701782 ])

In [32]:
rfc.predict([[1,0,0,-1,0]])

array([2])

In [33]:
rfc.predict([[0,0,0,-1,0]])

array([0])

Try to account for "other" favorite color

In [5]:
std_colors = ['blue','green','black','yellow','purple','red','orange','pink','other']

In [6]:
df_color_OCEAN = df[['FavColor','O','C','E','A','S']]

In [7]:
df_color_OCEAN['FavColor'] = df_color_OCEAN['FavColor'].str.lower().str.strip()

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [8]:
df_color_OCEAN['N'] = 0-df_color_OCEAN['S']
df_color_OCEAN = df_color_OCEAN.drop(columns='S')
df_color_OCEAN = df_color_OCEAN.dropna()

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [9]:
for i,color in enumerate(std_colors):
    df_color_OCEAN = df_color_OCEAN.replace(color,i)
    if (color=='other'):
        

FavColor         O         C         E         A         N
0                      red  0.871115 -1.163156  0.347041 -0.578990  0.242004
1                    green  0.432133  1.664499  0.662877 -0.578990 -0.096085
2                navy blue -0.884811 -0.456242  0.031205 -0.986787  0.242004
3                     blue -0.445830  0.957585  0.031205 -1.802382 -1.110352
4                   yellow -1.762774 -0.102785 -0.916303  0.644401  0.242004
5                     pink -1.323793 -0.809699  0.031205 -0.171193 -0.772263
6                    green  1.310097  0.957585  0.031205 -0.986787 -0.434174
7      grayish green-blue.  1.310097  0.957585  1.926221 -0.171193  1.594361
8                 lavender  0.432133  0.957585 -1.232139  0.236604 -1.448441
9                     teal -1.762774  1.311042 -1.863812 -1.802382 -0.434174
10                   green -0.445830  0.604128 -1.547975  1.867792 -1.448441
11                    blue -0.006848  0.957585  1.610385 -0.986787 -0.772263
12                  purple -0.884811  0.604128  1.294549 -1.802382 -0.772263
13                  purple  0.432133  0.957585  0.978713 -0.171193 -0.096085
14                rose red  0.432133  0.957585 -0.600467  1.052198  1.932450
15                     red  1.310097 -0.456242  1.294549  1.052198 -1.448441
16                    blue -0.445830 -0.456242 -0.916303  0.644401  0.580093
17                  purple -0.006848 -1.163156  0.662877 -0.171193 -0.096085
18                  purple  0.871115  0.604128 -0.916303  0.644401 -1.448441
19                     red  1.310097  1.311042  0.347041  1.459995 -0.096085
20                   green -0.445830 -0.456242 -0.600467  1.052198 -1.110352
22                  puroke  0.432133  0.957585  0.031205  1.052198 -0.096085
24                  purple -0.445830 -0.809699 -1.232139  1.459995  0.242004
25              iridescent  0.871115 -0.102785  0.662877 -1.802382  1.256272
26              chartreuse  0.871115  0.957585 -1.863812  0.236604  1.594361
27                   black  0.432133 -0.456242 -1.232139  0.644401 -1.110352
28                    blue  1.310097 -1.870069  1.610385  1.867792 -0.772263
29             purple, red  0.432133 -0.102785 -0.916303  1.459995 -0.772263
30                   green -0.884811  1.311042 -0.916303  0.236604 -1.448441
31                     red  0.871115  1.311042 -1.863812  1.867792 -1.110352
...                    ...       ...       ...       ...       ...       ...
16668                green -2.201756 -1.870069  0.347041 -1.394584 -0.096085
16669                green -0.006848 -0.102785  0.978713 -0.171193  0.242004
16670                 blue  0.871115  0.250672 -1.232139 -0.171193  1.256272
16671                 grey -0.006848 -1.516612  0.031205  1.052198  0.580093
16672                green -0.445830  0.957585  1.294549 -2.210179  0.918182
16673                 pink -0.445830  0.957585  0.662877 -0.578990 -0.434174
16674                 blue -0.884811  1.664499  1.294549 -0.578990 -0.096085
16675               purple -0.006848  0.250672 -1.863812  0.236604 -0.096085
16676                 blue -0.884811 -0.456242 -1.547975  1.867792  0.242004
16677                  red -0.445830  0.604128 -1.547975 -0.171193 -1.110352
16678             dark red -0.445830  0.250672 -1.547975  1.052198  1.256272
16679                 pink -0.445830  0.250672 -1.232139  0.644401  0.242004
16680                 blue  0.432133  0.957585 -1.863812  1.459995 -0.096085
16682           lime green -1.323793 -0.102785  0.978713  0.644401  1.256272
16683                 grey -1.762774 -0.456242 -0.284631  0.236604  1.932450
16684                 pink  0.871115  0.957585  0.978713  1.052198  1.256272
16685                green -0.884811 -1.163156 -1.232139 -0.171193  1.932450
16686    i don't have one.  0.432133 -0.456242  1.294549  0.644401 -0.772263
16687                 blue -2.201756  1.311042 -1.232139 -1.802382 -1.110352
16688               purple -0.884811 -1.870069 -1.547975  0.644401  1.594361
16689         